apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: BookStack is an opinionated documentation platform
      that provides a pleasant and simple out-of-the-box experience.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/20912696?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://www.bookstackapp.com/images/screenshots/page-view.png","https://www.bookstackapp.com/images/screenshots/page-edit.png","https://www.bookstackapp.com/images/screenshots/books-view.png","https://www.bookstackapp.com/images/screenshots/book-sorting.png","https://www.bookstackapp.com/images/screenshots/search.png"]'
    kubero.dev/template.source: https://github.com/BookStackApp/BookStack
    kubero.dev/template.categories: '["documentation"]'
    kubero.dev/template.title: Bookstack
    kubero.dev/template.website: https://www.bookstackapp.com/
  labels:
    manager: kubero
  name: bookstack
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: bookstack-mysql
        spec:
          rootPasswordSecretKeyRef:
            name: bookstack-mysql-root
            key: password
          database: bookstack
          username: bookstack
          passwordSecretKeyRef:
            name: bookstack-mysql-app
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          galera:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: bookstack-mysql-root
        type: Opaque
        stringData:
          password: bookstack
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: bookstack-mysql-app
        type: Opaque
        stringData:
          password: bookstack
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: Etc/UTC
  - name: APP_URL
    value: http://bookstack.example.com
  - name: APP_KEY
    value: base64:dm1hdnZvbmdvaDhxcTlnZXZkeXVzdmU4MnRnaWlhcDg=
  - name: DB_HOST
    value: bookstack-mysql
  - name: DB_PORT
    value: '3306'
  - name: DB_USERNAME
    value: bookstack
  - name: DB_PASSWORD
    value: bookstack
  - name: DB_DATABASE
    value: bookstack
  extraVolumes: []
  image:
    containerPort: '80'
    pullPolicy: Always
    repository: lscr.io/linuxserver/bookstack
    tag: latest
  name: bookstack
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
