apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Open Source Newsletter Tool.
    kubero.dev/template.icon: https://raw.githubusercontent.com/pentacent/keila/main/.github/assets/logo.svg
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '"https://www.keila.io/docs/configuration"'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/pentacent/keila/main/.github/assets/keila-20211203.jpg"]'
    kubero.dev/template.source: https://github.com/pentacent/keila
    kubero.dev/template.categories: '["communication", "work"]'
    kubero.dev/template.title: Keila
    kubero.dev/template.website: https://keila.io/
  labels:
    manager: kubero
  name: keila
spec:
  addons:
  - displayName: PostgreSQL (CloudNativePG)
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: Cluster
    resourceDefinitions:
      Cluster:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: keila-postgresql
        spec:
          instances: 1
          imageName: ghcr.io/cloudnative-pg/postgresql:16
          primaryUpdateStrategy: unsupervised
          storage:
            storageClass: fast
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
          bootstrap:
            initdb:
              database: postgresql
              owner: postgres
              secret:
                name: keila-postgresql-app
          enableSuperuserAccess: true
          superuserSecret:
            name: keila-postgresql-superuser
      superuserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: keila-postgresql-superuser
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: keila
      appUserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: keila-postgresql-app
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: keila
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: SECRET_KEY_BASE
    value: EiHaPZPt+t8SA9MuAIeVixPhDJI1T+XhYr1S54PcOAxNh+Z30PNWM/WSIhfREUvo
  - name: DB_URL
    value: postgres://postgres:keila@keila-postgresql-rw/postgresql
  - name: MAILER_SMTP_HOST
    value: 127.0.0.1
  - name: MAILER_SMTP_PORT
    value: '1025'
  - name: MAILER_SMTP_USER
    value: keila
  - name: MAILER_SMTP_PASSWORD
    value: keila
  - name: MAILER_SMTP_FROM_EMAIL
    value: noreply@localhost
  - name: KEILA_USER
    value: root@localhost
  - name: KEILA_PASSWORD
    value: keila
  extraVolumes: []
  image:
    containerPort: '4000'
    pullPolicy: Always
    repository: pentacent/keila
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: true
  name: keila
  serviceAccount:
    annotations: {}
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
