apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Leantime is a goals focused project management
      system for non-project managers. Building with ADHD, Autism, and dyslexia in
      mind.
    kubero.dev/template.icon: https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/leantime/icon.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/mywork.png","https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/dark.png","https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/kanban.png","https://raw.githubusercontent.com/Leantime/leantime/master/public/assets/images/Screenshots/timeline.png"]'
    kubero.dev/template.source: https://github.com/Leantime/leantime
    kubero.dev/template.categories: '["work", "development", "utilities"]'
    kubero.dev/template.title: Leantime
    kubero.dev/template.website: https://leantime.io/
  labels:
    manager: kubero
  name: leantime
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql'
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-root'
            key: password
          database: leantime
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          galera:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-root'
        type: Opaque
        stringData:
          password: leantime
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: LEAN_DB_HOST
    value: '{{KUBERO_APP_NAME}}-mysql'
  - name: LEAN_DB_USER
    value: root
  - name: LEAN_DB_PASSWORD
    value: leantime
  - name: LEAN_DB_DATABASE
    value: leantime
  - name: LEAN_EMAIL_RETURN
    value: changeme@local.local
  - name: LEAN_APP_URL
    value: '{{KUBERO_APP_URL}}'
  - name: LEAN_SESSION_PASSWORD
    value: leantime
  extraVolumes: []
  image:
    containerPort: '8080'
    repository: leantime/leantime
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: false
  name: leantime
  serviceAccount:
    annotations: {}
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
