apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: twofauth
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: 2FAuth is a web based self-hosted alternative
      to One Time Passcode (OTP) generators like Google Authenticator, designed for
      both mobile and desktop.
    kubero.dev/template.icon: https://docs.2fauth.app/static/2fauth_dark.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://user-images.githubusercontent.com/858858/100485897-18c21400-3102-11eb-9c72-ea0b1b46ef2e.png"]'
    kubero.dev/template.source: https://github.com/Bubka/2FAuth
    kubero.dev/template.categories: '["security", "accessories"]'
    kubero.dev/template.title: 2FAuth
    kubero.dev/template.website: https://docs.2fauth.app/
  labels:
    manager: kubero
spec:
  name: twofauth
  deploymentstrategy: docker
  envVars:
  - name: APP_NAME
    value: 2Fauth
  - name: APP_TIMEZONE
    value: UTC
  - name: APP_DEBUG
    value: 'false'
  - name: SITE_OWNER
    value: example@example.com
  - name: APP_KEY
    value: SomeRandomStringOf32CharsExactly
  - name: APP_URL
    value: https://twofauth.localhost
  - name: DB_CONNECTION
    value: mysql
  - name: DB_HOST
    value: '{{KUBERO_APP_NAME}}-mysql'
  - name: DB_PORT
    value: '3306'
  - name: DB_DATABASE
    value: twofauth
  - name: DB_USERNAME
    value: twofauth
  - name: DB_PASSWORD
    value: twofauth
  - name: APP_ENV
    value: production
  extraVolumes: []
  cronjobs: []
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql'
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-root'
            key: password
          database: twofauth
          username: twofauth
          passwordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-app'
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-root'
        type: Opaque
        stringData:
          password: twofauth
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-app'
        type: Opaque
        stringData:
          password: twofauth
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
  image:
    containerPort: '8000'
    pullPolicy: Always
    repository: registry.stackblaze.cloud/2fauth/2fauth
    tag: latest
    run:
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          add: []
          drop: []
        readOnlyRootFilesystem: false
        runAsGroup: 1000
        runAsNonRoot: false
        runAsUser: 1000
