apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Joomla is a free and open-source content management
      system for publishing web content on websites.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/751633?s=200&v=4
    kubero.dev/template.installation: Set JOOMLA_ADMIN_PASSWORD before first boot for auto-install.
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://upload.wikimedia.org/wikipedia/commons/9/96/Backend_Joomla_4_en.png"]'
    kubero.dev/template.source: https://github.com/joomla/joomla-cms
    kubero.dev/template.categories: '["cms"]'
    kubero.dev/template.title: Joomla
    kubero.dev/template.website: https://joomla.org
  name: joomla
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: joomla-db
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: joomla-db-root
            key: password
          database: joomla
          username: joomla
          passwordSecretKeyRef:
            name: joomla-db-app
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          galera:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: joomla-db-root
        type: Opaque
        stringData:
          password: joomla
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: joomla-db-app
        type: Opaque
        stringData:
          password: joomla
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: JOOMLA_DB_HOST
    value: joomla-db
  - name: JOOMLA_DB_USER
    value: joomla
  - name: JOOMLA_DB_PASSWORD
    value: joomla
  - name: JOOMLA_DB_NAME
    value: joomla
  - name: JOOMLA_DB_TYPE
    value: mysqli
  - name: JOOMLA_SITE_NAME
    value: Joomla
  - name: JOOMLA_ADMIN_USER
    value: Admin
  - name: JOOMLA_ADMIN_USERNAME
    value: admin
  - name: JOOMLA_ADMIN_PASSWORD
    value: change-me
  - name: JOOMLA_ADMIN_EMAIL
    value: admin@example.com
  image:
    containerPort: '80'
    repository: joomla
    tag: latest
  name: joomla
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 1Gi
  healthcheck:
    enabled: true
    path: /
    startupSeconds: 900
    timeoutSeconds: 5
    periodSeconds: 10
