apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: The open source password manager for teams
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/4386228?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot-login.png","https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot-share.png","https://raw.githubusercontent.com/passbolt/passbolt_styleguide/master/src/img/screenshots/teaser-screenshot4.png"]'
    kubero.dev/template.source: https://github.com/passbolt/passbolt_api
    kubero.dev/template.categories: '["security", "utilities"]'
    kubero.dev/template.title: Passbolt
    kubero.dev/template.website: https://www.passbolt.com
  name: passbolt
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: passbolt-mysql
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: passbolt-mysql-root
            key: password
          database: passbolt
          username: passbolt
          passwordSecretKeyRef:
            name: passbolt-mysql-app
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: passbolt-mysql-root
        type: Opaque
        stringData:
          password: changeme
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: passbolt-mysql-app
        type: Opaque
        stringData:
          password: changeme
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: APP_FULL_BASE_URL
    value: '{{KUBERO_APP_URL}}'
  - name: DATASOURCES_DEFAULT_HOST
    value: passbolt-mysql
  - name: DATASOURCES_DEFAULT_USERNAME
    value: passbolt
  - name: DATASOURCES_DEFAULT_PASSWORD
    value: changeme
  - name: DATASOURCES_DEFAULT_DATABASE
    value: passbolt
  - name: EMAIL_TRANSPORT_DEFAULT_HOST
    value: localhost
  - name: EMAIL_TRANSPORT_DEFAULT_PORT
    value: '25'
  - name: EMAIL_DEFAULT_FROM
    value: noreply@example.com
  healthcheck:
    enabled: true
    path: /healthcheck/status.json
    startupSeconds: 600
    timeoutSeconds: 5
    periodSeconds: 10
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    mountPath: /etc/passbolt/gpg
    name: passbolt-gpg-volume
    size: 1Gi
    storageClass: slow
  - accessModes:
    - ReadWriteOnce
    mountPath: /etc/passbolt/jwt
    name: passbolt-jwt-volume
    size: 1Gi
    storageClass: slow
  image:
    containerPort: '80'
    command:
    - sh
    - -c
    - mkdir -p /etc/passbolt/gpg /etc/passbolt/jwt && chown -R 33:33 /etc/passbolt/gpg
      /etc/passbolt/jwt && exec /docker-entrypoint.sh
    pullPolicy: Always
    repository: passbolt/passbolt
    run:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        readOnlyRootFilesystem: true
    tag: latest-ce
  name: passbolt
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
