apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: An open source virtual hand-drawn style whiteboard.
      Collaborative and end-to-end encrypted.
    kubero.dev/template.icon: https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/icon.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@1ca4dbd/services/excalidraw/demo.mp4", "https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/dashboard.png", "https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/screenshot-board.png", "https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/screenshot-architecture.png", "https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/screenshot-dark.png", "https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/excalidraw/screenshot-tools.png"]'
    kubero.dev/template.source: https://github.com/excalidraw/excalidraw
    kubero.dev/template.categories: '["documentation", "work", "collaboration"]'
    kubero.dev/template.title: Excalidraw
    kubero.dev/template.website: https://excalidraw.com/
  name: excalidraw
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars: []
  extraVolumes: []
  image:
    containerPort: '80'
    repository: excalidraw/excalidraw
    run:
      securityContext:
        readOnlyRootFilesystem: false
    tag: latest
  name: excalidraw
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
