apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Bluesky PDS (Personal Data Server). Your own
      Personal Data Server that is capable of federating with the wider Bluesky social
      network
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/94650532?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/bluesky-social/pds
    kubero.dev/template.categories: '["social"]'
    kubero.dev/template.title: BlueSky PDS
    kubero.dev/template.website: https://github.com/bluesky-social/pds
  name: bluesky-pds
spec:
  addons: []
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PDS_HOSTNAME
    value: '{{KUBERO_APP_HOST}}'
  - name: PDS_JWT_SECRET
    value: '{{KUBERO_GEN_ALNUM:32}}'
  - name: PDS_ADMIN_PASSWORD
    value: '{{KUBERO_GEN_ALNUM:32}}'
  - name: PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX
    value: ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d59f74e4312
  - name: PDS_DATA_DIRECTORY
    value: /pds
  - name: PDS_BLOBSTORE_DISK_LOCATION
    value: /pds/blocks
  - name: PDS_DID_PLC_URL
    value: https://plc.bsky-sandbox.dev
  - name: PDS_BSKY_APP_VIEW_URL
    value: https://api.bsky-sandbox.dev
  - name: PDS_BSKY_APP_VIEW_DID
    value: did:web:api.bsky-sandbox.dev
  - name: PDS_CRAWLERS
    value: https://bgs.bsky-sandbox.dev
  - name: LOG_ENABLED
    value: 'true'
  - name: PDS_INVITE_REQUIRED
    value: 'false'
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /pds
    name: bsk-data
    size: 40Gi
  healthcheck:
    enabled: true
    path: /xrpc/_health
    startupSeconds: 600
    timeoutSeconds: 5
    periodSeconds: 10
  image:
    containerPort: '3000'
    pullPolicy: Always
    repository: ghcr.io/bluesky-social/pds
    tag: latest
  name: bluesky-pds
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: '1'
      memory: 1Gi
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
