apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: An easy-to-use photo-management-system to manage
      and share photos.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/37916028?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://lycheeorg.github.io/assets/3.BzY-5hAj.jpg"]'
    kubero.dev/template.source: https://github.com/LycheeOrg/Lychee
    kubero.dev/template.categories: '["data"]'
    kubero.dev/template.title: Lychee
    kubero.dev/template.website: https://lycheeorg.github.io/
  labels:
    manager: kubero
  name: lychee
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql'
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-root'
            key: password
          database: lychee
          username: lychee
          passwordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-app'
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-root'
        type: Opaque
        stringData:
          password: lychee
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-app'
        type: Opaque
        stringData:
          password: lychee
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PHP_TZ
    value: UTC
  - name: APP_ENV
    value: local
  - name: APP_KEY
    value: base64:B0SHakyMaw8rozeNKm+XcT1ZukIc9xSNPghJiWh9ivc=
  - name: STARTUP_DELAY
    value: '5'
  - name: TRUSTED_PROXIES
    value: '*'
  - name: APP_FORCE_HTTPS
    value: 'false'
  - name: APP_URL
    value: https://lychee.localhost
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: DB_CONNECTION
    value: mysql
  - name: DB_HOST
    value: '{{KUBERO_APP_NAME}}-mysql'
  - name: DB_PORT
    value: '3306'
  - name: DB_DATABASE
    value: lychee
  - name: DB_USERNAME
    value: lychee
  - name: DB_PASSWORD
    value: lychee
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /app/public/uploads
    name: lychee-upload-volume
    size: 1Gi
    storageClass: slow
  image:
    containerPort: '8000'
    pullPolicy: Always
    repository: lycheeorg/lychee
    tag: latest
    command:
    - sh
    - -c
    - mkdir -p /app/public/uploads && chown -R 1000:1000 /app/public/uploads && chmod
      0775 /app/public/uploads && until mysqladmin ping -h"$DB_HOST" -P"$DB_PORT"
      -u"$DB_USERNAME" -p"$DB_PASSWORD" --silent; do sleep 3; done && exec /usr/local/bin/entrypoint.sh
      php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000
    run:
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        readOnlyRootFilesystem: false
  name: lychee
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
