apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: syncthing
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: "Continuous file synchronization \u2014 decentralized\
      \ alternative to proprietary sync services."
    kubero.dev/template.icon: https://raw.githubusercontent.com/stackblaze/stack-templates/main/services/syncthing/icon.png
    kubero.dev/template.installation: Access the web UI to pair devices and configure
      sync folders.
    kubero.dev/template.links: '["https://docs.syncthing.net/"]'
    kubero.dev/template.screenshots: '["https://docs.syncthing.net/_images/gs1-gui.png"]'
    kubero.dev/template.source: https://github.com/syncthing/syncthing
    kubero.dev/template.categories: '["storage", "utilities"]'
    kubero.dev/template.title: Syncthing
    kubero.dev/template.website: https://syncthing.net/
  labels:
    manager: kubero
spec:
  name: syncthing
  deploymentstrategy: docker
  addons: []
  envVars:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /var/syncthing
    name: '{{KUBERO_APP_NAME}}-config'
    size: 2Gi
    storageClass: shared
  cronjobs: []
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
  image:
    containerPort: '8384'
    pullPolicy: Always
    repository: registry.stackblaze.cloud/syncthing/syncthing
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: false
