apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: documenso
  annotations:
    kubero.dev/template.architecture: '["linux/amd64", "linux/arm64/v8"]'
    kubero.dev/template.description: The Open Source DocuSign Alternative.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/127681099
    kubero.dev/template.installation: Configure NEXT_PRIVATE_SMTP_* for production
      email delivery.
    kubero.dev/template.links: '["https://docs.documenso.com/"]'
    kubero.dev/template.screenshots: '[]'
    kubero.dev/template.source: https://github.com/documenso/documenso
    kubero.dev/template.categories: '["security", "work", "productivity"]'
    kubero.dev/template.title: Documenso
    kubero.dev/template.website: https://www.documenso.com/
  labels:
    manager: kubero
spec:
  name: documenso
  deploymentstrategy: docker
  envVars:
  - name: NEXTAUTH_URL
    value: '{{KUBERO_APP_URL}}'
  - name: NEXTAUTH_SECRET
    value: random64
  - name: NEXT_PRIVATE_ENCRYPTION_KEY
    value: DYKf6hj9+o9hrcnpl/ELUaRjwg13VKPhReE7sjv08rGLy1SZGLpXBLkvjNWy8UK90E4le1+k9rRQNFGGuB83USHXJU45llBBpjqZctDXHAU=
  - name: NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY
    value: xFtITgOSSvu/bTTJ11G/czyXlvhF8txPhr2GwSTQUm/+m6YLIfrC/LTgHq2yFi9l+KBWN+Wx5YgRFoWOvdkePs5N31/1RBhx3/qApQ2lIbY=
  - name: NEXT_PUBLIC_WEBAPP_URL
    value: '{{KUBERO_APP_URL}}'
  - name: NEXT_PRIVATE_INTERNAL_WEBAPP_URL
    value: '{{KUBERO_APP_URL}}'
  - name: NEXT_PRIVATE_DATABASE_URL
    value: postgresql://documenso:documenso@documenso-postgresql-rw:5432/documenso
  - name: NEXT_PRIVATE_DIRECT_DATABASE_URL
    value: postgresql://documenso:documenso@documenso-postgresql-rw:5432/documenso
  - name: NEXT_PRIVATE_SMTP_TRANSPORT
    value: smtp-auth
  - name: NEXT_PRIVATE_SMTP_HOST
    value: smtp.example.com
  - name: NEXT_PRIVATE_SMTP_PORT
    value: '587'
  - name: NEXT_PRIVATE_SMTP_USERNAME
    value: noreply@example.com
  - name: NEXT_PRIVATE_SMTP_PASSWORD
    value: replace-me
  - name: NEXT_PRIVATE_SMTP_FROM_NAME
    value: Documenso
  - name: NEXT_PRIVATE_SMTP_FROM_ADDRESS
    value: noreply@example.com
  - name: DOCUMENSO_DISABLE_TELEMETRY
    value: 'true'
  extraVolumes: []
  cronjobs: []
  addons:
  - displayName: PostgreSQL (CloudNativePG)
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: Cluster
    resourceDefinitions:
      Cluster:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: documenso-postgresql
        spec:
          instances: 3
          imageName: ghcr.io/cloudnative-pg/postgresql:16
          primaryUpdateStrategy: unsupervised
          storage:
            storageClass: fast
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
          bootstrap:
            initdb:
              database: documenso
              owner: documenso
              secret:
                name: documenso-postgresql-app
              postInitApplicationSQL:
              - GRANT ALL ON SCHEMA public TO documenso
              - GRANT CREATE ON SCHEMA public TO documenso
              - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO documenso
          enableSuperuserAccess: true
          superuserSecret:
            name: documenso-postgresql-superuser
      superuserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: documenso-postgresql-superuser
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: documenso
      appUserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: documenso-postgresql-app
        type: kubernetes.io/basic-auth
        stringData:
          username: documenso
          password: documenso
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 2Gi
  healthcheck:
    enabled: true
    path: /
    startupSeconds: 600
    timeoutSeconds: 5
    periodSeconds: 10
  image:
    containerPort: '3000'
    pullPolicy: Always
    repository: documenso/documenso
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: false
