apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: piwigo
  annotations:
    kubero.dev/template.architecture: '["linux/amd64", "linux/arm64"]'
    kubero.dev/template.description: Manage your photos with Piwigo, a full featured
      open source photo gallery application for the web.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/9326886
    kubero.dev/template.installation: This app requires a manual step to configure
      the MySQL database.
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://piwigo.org/plugins/piwigo-piwigodotorg//images/home/responsive-screens.png"]'
    kubero.dev/template.source: https://github.com/Piwigo/Piwigo
    kubero.dev/template.categories: '["utilities"]'
    kubero.dev/template.title: Piwigo
    kubero.dev/template.website: https://piwigo.org/
  labels:
    manager: kubero
spec:
  name: piwigo
  deploymentstrategy: docker
  envVars: []
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /config
    name: piwigo-config-volume
    size: 1Gi
    storageClass: slow
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /gallery
    name: piwigo-gallery-volume
    size: 1Gi
    storageClass: slow
  cronjobs: []
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: piwigo-mysql
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: piwigo-mysql-root
            key: password
          database: piwigo
          username: piwigo
          passwordSecretKeyRef:
            name: piwigo-mysql-app
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: piwigo-mysql-root
        type: Opaque
        stringData:
          password: piwigo
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: piwigo-mysql-app
        type: Opaque
        stringData:
          password: piwigo
    version:
      latest: 0.1.5
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
  image:
    containerPort: '80'
    pullPolicy: Always
    repository: lscr.io/linuxserver/piwigo
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: true
