apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: A self hosted platform for tracking various facets
      of your life - media, fitness etc.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/60938164?v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/ignisda/ryot/main/apps/website/public/cta-image.png"]'
    kubero.dev/template.source: https://github.com/ignisda/ryot
    kubero.dev/template.categories: '["productivity"]'
    kubero.dev/template.title: Ryot
    kubero.dev/template.website: https://github.com/ignisda/ryot
  labels:
    manager: kubero
  name: ryot
spec:
  addons:
  - displayName: PostgreSQL (CloudNativePG)
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: Cluster
    resourceDefinitions:
      Cluster:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql'
        spec:
          instances: 1
          imageName: ghcr.io/cloudnative-pg/postgresql:16
          primaryUpdateStrategy: unsupervised
          storage:
            storageClass: fast
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
          bootstrap:
            initdb:
              database: ryot
              owner: ryot
              secret:
                name: '{{KUBERO_APP_NAME}}-postgresql-app'
              postInitApplicationSQL:
              - GRANT ALL ON SCHEMA public TO ryot
              - GRANT CREATE ON SCHEMA public TO ryot
              - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ryot
          enableSuperuserAccess: true
          superuserSecret:
            name: '{{KUBERO_APP_NAME}}-postgresql-superuser'
      superuserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql-superuser'
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: ryot
      appUserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql-app'
        type: kubernetes.io/basic-auth
        stringData:
          username: ryot
          password: ryot
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DATABASE_URL
    value: postgres://ryot:ryot@{{KUBERO_APP_NAME}}-postgresql-rw:5432/ryot
  - name: FRONTEND_URL
    value: '{{KUBERO_APP_URL}}'
  - name: SERVER_ADMIN_ACCESS_TOKEN
    value: random64
  - name: DISABLE_TELEMETRY
    value: 'true'
  extraVolumes: []
  healthcheck:
    enabled: true
    path: /
    startupSeconds: 300
    timeoutSeconds: 5
    periodSeconds: 10
  image:
    containerPort: '8000'
    pullPolicy: Always
    repository: ghcr.io/ignisda/ryot
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: false
  name: ryot
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
