apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: AFFiNE is a next-gen knowledge base that brings
      planning, sorting and creating all together
    kubero.dev/template.icon: https://raw.githubusercontent.com/toeverything/AFFiNE/master/packages/frontend/admin/src/modules/auth/logo.svg
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '["https://docs.affine.pro/docs/hello-bonjour-aloha-%E4%BD%A0%E5%A5%BD"]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/toeverything/AFFiNE
    kubero.dev/template.categories: '["utilities", "work"]'
    kubero.dev/template.title: AFFiNE
    kubero.dev/template.website: https://affine.pro/
  labels:
    manager: kubero
  name: affine
spec:
  addons:
  - displayName: PostgreSQL (CloudNativePG)
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: Cluster
    resourceDefinitions:
      Cluster:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: affine-postgresql
        spec:
          instances: 1
          imageName: ghcr.io/cloudnative-pg/postgresql:16
          primaryUpdateStrategy: unsupervised
          storage:
            storageClass: fast
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          bootstrap:
            initdb:
              database: postgresql
              owner: affine
              secret:
                name: affine-postgresql-app
          enableSuperuserAccess: true
          superuserSecret:
            name: affine-postgresql-superuser
      superuserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: affine-postgresql-superuser
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: afffine
      appUserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: affine-postgresql-app
        type: kubernetes.io/basic-auth
        stringData:
          username: affine
          password: afffine
  - displayName: Redis
    env: []
    icon: /img/addons/Redis.png
    id: kubero-operator
    kind: KuberoRedis
    resourceDefinitions:
      KuberoRedis:
        apiVersion: application.kubero.dev/v1alpha1
        kind: KuberoRedis
        metadata:
          name: affine-redis
        spec:
          redis:
            architecture: replication
            global:
              redis:
                password: affine
            master:
              persistence:
                size: 1Gi
            replica:
              persistence:
                size: 1Gi
              replicaCount: 1
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: NODE_OPTIONS
    value: --import=./scripts/register.js
  - name: REDIS_SERVER_HOST
    value: affine-redis-master
  - name: DATABASE_URL
    value: postgres://affine:afffine@affine-postgresql-rw:5432/postgresql
  - name: NODE_ENV
    value: production
  - name: AFFINE_ADMIN_EMAIL
    value: admin@admin.com
  - name: AFFINE_ADMIN_PASSWORD
    value: admin
  - name: TELEMETRY_ENABLE
    value: 'false'
  - name: REDIS_SERVER_PASSWORD
    value: affine
  extraVolumes:
  - accessMode: ReadWriteOnce
    accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /root/.affine
    name: affine-volume
    size: 1Gi
  image:
    containerPort: '3010'
    pullPolicy: Always
    repository: ghcr.io/toeverything/affine-graphql
    tag: stable
  name: affine
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
