apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: A better onlne commenting experience from Vox
      Media
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/9255912?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '["https://docs.coralproject.net/","https://github.com/coralproject/talk/blob/main/docs/docs/environment-variables.md"]'
    kubero.dev/template.screenshots: 'null'
    kubero.dev/template.source: https://github.com/coralproject/talk
    kubero.dev/template.categories: '["social","communication"]'
    kubero.dev/template.title: Coral
    kubero.dev/template.website: https://coralproject.net
  name: coral
spec:
  addons:
  - displayName: Valkey
    env: []
    icon: /img/addons/redis.svg
    id: kubero-operator
    kind: Valkey
    resourceDefinitions:
      Valkey:
        apiVersion: rds.valkey.buf.red/v1alpha1
        kind: Valkey
        metadata:
          name: coral-valkey
        spec:
          version: "8.0"
          arch: replica
          replicas:
            shards: 1
            replicasOfShard: 1
          access:
            serviceType: ClusterIP
          storage:
            capacity: 1Gi
            storageClassName: fast
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
  - displayName: Document DB
    env: []
    icon: /img/addons/mongo.svg
    id: documentdb-operator
    kind: DocumentDB
    resourceDefinitions:
      DocumentDB:
        apiVersion: documentdb.io/preview
        kind: DocumentDB
        metadata:
          name: coral-documentdb
        spec:
          nodeCount: 1
          instancesPerNode: 1
          documentDbCredentialSecret: documentdb-credentials
          resource:
            storage:
              pvcSize: 1Gi
              storageClass: default
          exposeViaService:
            serviceType: ClusterIP
      credentialSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: documentdb-credentials
        type: Opaque
        stringData:
          username: mongoadmin
          password: changeme
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: SIGNING_SECRET
    value: change-me-to-make-me-secure
  - name: REDIS_URI
    value: redis://rfr-coral-valkey-readwrite:6379
  - name: MONGODB_URI
    value: mongodb://mongoadmin:changeme@documentdb-service-coral-documentdb:10260/coral?directConnection=true&authMechanism=SCRAM-SHA-256&tls=true&tlsAllowInvalidCertificates=true&replicaSet=rs0
  - name: NODE_ENV
    value: production
  - name: LOGGING_LEVEL
    value: info
  extraVolumes: []
  image:
    containerPort: '8080'
    repository: coralproject/talk
    tag: '7'
  name: coral
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
