apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Self-hosted monitoring tool like "Uptime Robot".
    kubero.dev/template.icon: https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@3664d86/services/uptime-kuma/icon.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@3664d86/services/uptime-kuma/demo.mp4", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@3664d86/services/uptime-kuma/dashboard.png", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@3664d86/services/uptime-kuma/screenshot-monitor-detail.png", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@3664d86/services/uptime-kuma/screenshot-status-page.png"]'
    kubero.dev/template.source: https://github.com/louislam/uptime-kuma
    kubero.dev/template.categories: '["monitoring"]'
    kubero.dev/template.title: Uptime Kuma
    kubero.dev/template.website: https://uptime.kuma.pet
  name: uptime-kuma
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql'
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-root'
            key: password
          database: uptimekuma
          username: uptimekuma
          passwordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-app'
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-root'
        type: Opaque
        stringData:
          password: uptimekuma
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-app'
        type: Opaque
        stringData:
          password: uptimekuma
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: DB_TYPE
    value: mariadb
  - name: DB_MYSQL_HOST
    value: '{{KUBERO_APP_NAME}}-mysql'
  - name: DB_MYSQL_PORT
    value: '3306'
  - name: DB_MYSQL_USER
    value: uptimekuma
  - name: DB_MYSQL_PASSWORD
    value: uptimekuma
  - name: DB_MYSQL_DATABASE
    value: uptimekuma
  extraVolumes: []
  image:
    containerPort: '3001'
    repository: registry.stackblaze.cloud/louislam/uptime-kuma
    tag: latest
    run:
      securityContext:
        readOnlyRootFilesystem: false
  name: uptime-kuma
  web:
    replicaCount: 2
  worker:
    replicaCount: 0
