apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Ghost is a powerful app for new-media creators
      to publish, share, and grow a business around their content.
    kubero.dev/template.icon: https://ghost.org/images/logos/ghost-logo-orb.png
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://user-images.githubusercontent.com/353959/169805900-66be5b89-0859-4816-8da9-528ed7534704.png"]'
    kubero.dev/template.source: https://github.com/TryGhost/Ghost
    kubero.dev/template.categories: '["cms", "work"]'
    kubero.dev/template.title: Ghost
    kubero.dev/template.website: https://ghost.org/
  name: ghost
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: ghost-mysql
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: ghost-mysql-root
            key: password
          database: ghost
          username: ghost
          passwordSecretKeyRef:
            name: ghost-mysql-app
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          galera:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ghost-mysql-root
        type: Opaque
        stringData:
          password: ghost
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: ghost-mysql-app
        type: Opaque
        stringData:
          password: ghost
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: database__client
    value: mysql
  - name: database__connection__host
    value: ghost-mysql
  - name: database__connection__user
    value: ghost
  - name: database__connection__password
    value: ghost
  - name: database__connection__database
    value: ghost
  - name: url
    value: http://ghost.lacolhost.com:81
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /var/lib/ghost/content
    name: ghost-volume
    size: 1Gi
  image:
    containerPort: '2368'
    repository: ghost
    tag: latest
  name: ghost
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
