apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: LimeSurvey is the simple, quick and anonymous
      online survey tool that's bursting with juicy insights.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/1364105?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '"https://manual.limesurvey.org/LimeSurvey_Manual"'
    kubero.dev/template.screenshots: '["https://manual.limesurvey.org/images/1/15/Surveys-alternative_button.png","https://manual.limesurvey.org/images/5/50/Newsurveyscreen.png"]'
    kubero.dev/template.source: https://github.com/LimeSurvey/LimeSurvey
    kubero.dev/template.categories: '["communication", "utilities"]'
    kubero.dev/template.title: LimeSurvey
    kubero.dev/template.website: https://www.limesurvey.org
  labels:
    manager: kubero
  name: limesurvey
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: limesurvey-mysql
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: limesurvey-mysql-root
            key: password
          database: limesurvey
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 3
          galera:
            enabled: true
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: limesurvey-mysql-root
        type: Opaque
        stringData:
          password: root
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: LIMESURVEY_DB_HOST
    value: limesurvey-mysql
  - name: LIMESURVEY_DB_PASSWORD
    value: root
  - name: LIMESURVEY_ADMIN_USER
    value: root
  - name: LIME_ADMIN_PASSWORD
    value: root
  - name: LIMESURVEY_ADMIN_NAME
    value: Lime Administrator
  - name: LIMESURVEY_ADMIN_EMAIL
    value: lime@lime.me
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /var/www/html
    name: limesurvey-volume
    size: 1Gi
  image:
    containerPort: '8082'
    repository: adamzammit/limesurvey
    tag: latest
  name: limesurvey
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
