apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Photoview is a simple and user-friendly photo
      gallery that is made for photographers and aims to provide an easy and fast
      way to navigate directories.
    kubero.dev/template.icon: https://avatars.githubusercontent.com/u/75802894?s=200&v=4
    kubero.dev/template.installation: ''
    kubero.dev/template.links: '[]'
    kubero.dev/template.screenshots: '["https://raw.githubusercontent.com/photoview/photoview/master/screenshots/timeline.png"]'
    kubero.dev/template.source: https://github.com/photoview/photoview
    kubero.dev/template.categories: '["utilities"]'
    kubero.dev/template.title: Photoview
    kubero.dev/template.website: https://photoview.github.io/
  name: photoview
spec:
  addons:
  - displayName: MariaDB
    env: []
    icon: /img/addons/mysql.svg
    id: kubero-operator
    kind: MariaDB
    resourceDefinitions:
      MariaDB:
        apiVersion: k8s.mariadb.com/v1alpha1
        kind: MariaDB
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql'
        spec:
          metrics:
            enabled: true
          rootPasswordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-root'
            key: password
          database: photoview
          username: photoview
          passwordSecretKeyRef:
            name: '{{KUBERO_APP_NAME}}-mysql-app'
            key: password
          storage:
            size: 5Gi
            storageClassName: fast
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
      rootSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-root'
        type: Opaque
        stringData:
          password: rootpw
      appSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-mysql-app'
        type: Opaque
        stringData:
          password: photoview
  cronjobs: []
  deploymentstrategy: docker
  envVars:
  - name: PROC_TYPE
    value: web
  - name: PORT
    value: '8080'
  - name: PHOTOVIEW_DATABASE_DRIVER
    value: mysql
  - name: PHOTOVIEW_MYSQL_URL
    value: photoview:photoview@tcp({{KUBERO_APP_NAME}}-mysql)/photoview
  - name: PHOTOVIEW_LISTEN_IP
    value: 0.0.0.0
  - name: PHOTOVIEW_LISTEN_PORT
    value: '8080'
  - name: PHOTOVIEW_MEDIA_CACHE
    value: /tmp
  extraVolumes:
  - accessModes:
    - ReadWriteOnce
    emptyDir: false
    mountPath: /photoview/images
    name: photoview-images
    size: 1Gi
    storageClass: lite
  image:
    containerPort: '8080'
    repository: viktorstrate/photoview
    tag: '2'
    run:
      securityContext:
        readOnlyRootFilesystem: false
  name: photoview
  web:
    replicaCount: 1
  worker:
    replicaCount: 0
