apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
  name: twenty
  annotations:
    kubero.dev/template.architecture: '[]'
    kubero.dev/template.description: Building a modern alternative to Salesforce,
      powered by the community.
    kubero.dev/template.icon: https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/icon.png
    kubero.dev/template.installation: 'All available environment variables are described
      here : https://twenty.com/developers/section/self-hosting/self-hosting-var'
    kubero.dev/template.links: '["https://twenty.com/user-guide", "https://twenty.com/developers"]'
    kubero.dev/template.screenshots: '["https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/demo.mp4", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/dashboard.png", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/screenshot-people.png", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/screenshot-opportunities.png", "https://cdn.jsdelivr.net/gh/stackblaze/stack-templates@54dbcb3cf1eb0643ab8ec7b9297ceabcd652f694/services/twenty/screenshot-tasks.png"]'
    kubero.dev/template.source: https://github.com/twentyhq/twenty
    kubero.dev/template.categories: '["productivity", "work" ]'
    kubero.dev/template.title: twenty
    kubero.dev/template.website: https://twenty.com/
  labels:
    manager: kubero
spec:
  name: twenty
  deploymentstrategy: docker
  envVars:
  - name: FRONT_BASE_URL
    value: '{{KUBERO_APP_URL}}'
  - name: SERVER_URL
    value: '{{KUBERO_APP_URL}}'
  - name: ENABLE_DB_MIGRATIONS
    value: 'true'
  - name: CACHE_STORAGE_TYPE
    value: redis
  - name: REDIS_URL
    value: redis://rfr-{{KUBERO_APP_NAME}}-valkey-readwrite:6379
  - name: API_RATE_LIMITING_TTL
    value: '100'
  - name: API_RATE_LIMITING_LIMIT
    value: '100'
  - name: APP_SECRET
    value: base64:Mnl3bDdlYjY2bzBmcWMzanE3dDhiN3BxY2ZqZzh3bmM=
  - name: POSTGRES_ADMIN_PASSWORD
    value: twenty
  - name: PG_DATABASE_URL
    value: postgres://twenty:twenty@{{KUBERO_APP_NAME}}-postgresql-rw:5432/twenty
  - name: IS_SIGN_UP_DISABLED
    value: 'false'
  - name: PASSWORD_RESET_TOKEN_EXPIRES_IN
    value: 5m
  - name: WORKSPACE_INACTIVE_DAYS_BEFORE_NOTIFICATION
    value: '365'
  - name: WORKSPACE_INACTIVE_DAYS_BEFORE_SOFT_DELETION
    value: '380'
  - name: WORKSPACE_INACTIVE_DAYS_BEFORE_DELETION
    value: '400'
  - name: STORAGE_TYPE
    value: local
  - name: MESSAGE_QUEUE_TYPE
    value: pg-boss
  - name: SIGN_IN_PREFILLED
    value: 'false'
  - name: DEBUG_MODE
    value: 'false'
  - name: TELEMETRY_ENABLED
    value: 'true'
  - name: NODE_OPTIONS
    value: --max-old-space-size=1536
  extraVolumes:
  - accessModes:
    - ReadWriteMany
    emptyDir: false
    mountPath: /app/docker-data/
    name: '{{KUBERO_APP_NAME}}-data-volume'
    size: 1Gi
    storageClass: shared
  cronjobs: []
  addons:
  - displayName: PostgreSQL (CloudNativePG)
    env: []
    icon: /img/addons/pgsql.svg
    id: kubero-operator
    kind: Cluster
    resourceDefinitions:
      Cluster:
        apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql'
        spec:
          instances: 3
          imageName: ghcr.io/cloudnative-pg/postgresql:16
          primaryUpdateStrategy: unsupervised
          storage:
            storageClass: smart
            size: 5Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: '1'
              memory: 1Gi
          bootstrap:
            initdb:
              database: twenty
              owner: twenty
              secret:
                name: '{{KUBERO_APP_NAME}}-postgresql-app'
              postInitApplicationSQL:
              - GRANT ALL ON SCHEMA public TO twenty
              - GRANT CREATE ON SCHEMA public TO twenty
              - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO twenty
          enableSuperuserAccess: true
          superuserSecret:
            name: '{{KUBERO_APP_NAME}}-postgresql-superuser'
      superuserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql-superuser'
        type: kubernetes.io/basic-auth
        stringData:
          username: postgres
          password: twenty
      appUserSecret:
        apiVersion: v1
        kind: Secret
        metadata:
          name: '{{KUBERO_APP_NAME}}-postgresql-app'
        type: kubernetes.io/basic-auth
        stringData:
          username: twenty
          password: twenty
  - displayName: Valkey
    env: []
    icon: /img/addons/redis.svg
    id: kubero-operator
    kind: Valkey
    resourceDefinitions:
      Valkey:
        apiVersion: rds.valkey.buf.red/v1alpha1
        kind: Valkey
        metadata:
          name: '{{KUBERO_APP_NAME}}-valkey'
        spec:
          version: '8.0'
          arch: failover
          replicas:
            shards: 1
            replicasOfShard: 2
          sentinel:
            replicas: 3
            quorum: 2
          access:
            serviceType: ClusterIP
          storage:
            capacity: 1Gi
            storageClassName: fast
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 256Mi
  web:
    replicaCount: 2
  worker:
    replicaCount: 1
  image:
    containerPort: '3000'
    pullPolicy: Always
    repository: registry.stackblaze.cloud/twentycrm/twenty
    tag: v2.16.1
    run:
      securityContext:
        readOnlyRootFilesystem: false
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: '1'
      memory: 2Gi
  healthcheck:
    enabled: true
    path: /
    startupSeconds: 600
    timeoutSeconds: 5
    periodSeconds: 10
